name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    name: Build dist & publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Install build dependencies & build
      run: |
        python -m pip install --upgrade pip
        pip install requirements.txt
        pip install setuptools wheel
        python setup.py bdist_wheel

    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
